title: Live for leave
author: floin
email: v20130402@yeah.net
description: > # this means to ignore newlines until "baseurl:"
  Live for leave, this is your entire life.
  凡事豫则立，不豫则废。言前定则不跲，事前定则不困，行前定则不疚， 道前定则不穷。
  floin.github.io is a lite personal blog for sharing curio and ideas.

twitter_username: Inzair_ckg
github_username:  floin

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
